server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://3.108.108.53:5432/test-netfilx-dgs
    username: admin
    password: 1234qwer$$
  jpa:
    properties:
      repository_package: com.iamdinuth.commonmicroservice.data.repository
      hibernate:
#        default_schema: upwork
        dialect: org.hibernate.dialect.PostgreSQLDialect # org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    com:
      iamdinuth:
        countrymicroservice: DEBUG

keycloak:
  realm: Test
  auth-server-url: http://localhost:8082
  ssl-required: external
  resource: test-backend
  credentials:
    secret: 0yIsBx0rB9PmUVurDjMWK4azc4tgDvIJ
  use-resource-role-mappings: false
  public-client: true
  bearer-only: true


dgs:
  graphql:
    cors:
      allow-credentials: true
      allowed-origins: http://localhost:5173
      allowed-methods:
        - GET
        - POST
        - OPTIONS
      allowed-headers:
        - Content-Type
        - Authorization


